/**
 * Strategy types for the new trading system
 */
export type NewStrategyType = 'CORE_TREND' | 'SQUEEZE';

/**
 * Trade direction
 */
export type TradeDirection = 'LONG' | 'SHORT';

/**
 * Funding overlay action
 */
export type FundingAction = 'ALLOW' | 'TIGHTEN' | 'BLOCK';

/**
 * Trading Signal generated by strategies
 * Based on improve.md specifications
 *
 * IMPORTANT CONVENTIONS (P1-4, P2-1):
 * - ATR values are calculated from the LAST CONFIRMED candle of entry TF
 *   (Core Trend: 4H, Squeeze: 1H). ATR is NOT recalculated during position lifetime.
 * - TP1 is executed via MARKET ORDER when price reaches tp1Price (not limit order).
 *   Position manager checks price every 10 seconds and triggers partial close.
 * - All R values (tp1R, etc.) are NET after commission/slippage.
 */
export interface TradingSignal {
  /** Whether a valid signal was detected */
  detected: boolean;

  /** Strategy that generated this signal */
  strategyType: NewStrategyType;

  /** Sub-strategy or specific pattern (e.g., 'EMA_CROSSOVER', 'COMPRESSION_BREAKOUT') */
  subStrategy: string;

  /** Trading symbol */
  symbol: string;

  /** Trade direction */
  direction: TradeDirection;

  /** Entry price (current or limit) */
  entryPrice: number;

  /** Stop loss price */
  slPrice: number;

  /** ATR multiplier used for SL calculation */
  slAtrMult: number;

  /** Take profit 1 price (partial exit) */
  tp1Price: number;

  /** Percentage of position to close at TP1 (0.25 - 0.40) */
  tp1QtyPercent: number;

  /** ATR multiplier for trailing stop */
  trailAtrMult: number;

  /** Time stop in bars for entry timeframe (Core Trend: 30 4H bars) */
  timeStopBars?: number;

  /** Funding overlay action */
  fundingAction: FundingAction;

  /** Signal confidence (0-100) */
  confidence: number;

  /** Additional metadata for logging and analysis */
  metadata: SignalMetadata;
}

/**
 * Signal metadata for debugging and analysis
 */
export interface SignalMetadata {
  // Trend indicators
  ema50?: number;
  ema200?: number;
  emaFast?: number;
  emaSlow?: number;

  // Volatility indicators
  atr?: number;
  atrPercent?: number;
  bbWidth?: number;
  bbWidthPercentile?: number;

  // Momentum/direction indicators
  adx?: number;

  // Funding
  fundingRate?: number;
  fundingPctl?: number;

  // Squeeze specific
  compressionDetected?: boolean;
  breakoutConfirmed?: boolean;
  boxHigh?: number;
  boxLow?: number;

  // Core Trend specific
  trend1d?: 'UP' | 'DOWN' | 'NEUTRAL';
  pullbackDepth?: number;

  // Entry quality
  entryQuality?: 'HIGH' | 'MEDIUM' | 'LOW';

  // Leverage and position sizing
  leverage?: number;
  marginUsd?: number;
  positionSizeUsd?: number;

  // Timestamps
  signalTime?: number;

  // Custom fields
  [key: string]: any;
}

/**
 * Partial signal for intermediate processing
 */
export interface PartialSignal {
  detected: boolean;
  direction?: TradeDirection;
  entryPrice?: number;
  slPrice?: number;
  confidence?: number;
  metadata?: Partial<SignalMetadata>;
}
